name: Bump version
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        env: 
          TAG_PREFIX: '6.2-beta'
        run: | 
              set -x
              git config --global user.email "exo-swf@exoplatform.com"
              git config --global user.name "eXo Software Factory"
              CURRENT_TAG=$(git tag -l | grep -P ${TAG_PREFIX} | tail -n 1)
              if [ -z "${CURRENT_TAG}" ]; then
                NEW_TAG="${TAG_PREFIX}01"
              else 
                INDEX=$(echo $CURRENT_TAG | sed "s|.*${TAG_PREFIX}||")
                ((INDEX++))
                [ "${INDEX}" -lt "10" ] && INDEX="0${INDEX}"
                NEW_TAG="${TAG_PREFIX}${INDEX}"
              fi
              git tag ${NEW_TAG} -m '' && git push origin ${NEW_TAG}
        shell: bash      