name: Bump version
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        env: 
          TAG_PREFIX: '6.2-beta'
        run: | 
              git config --global user.email "exo-swf@exoplatform.com"
              git config --global user.name "eXo Software Factory"
              echo "CURRENT_TAG=$(git for-each-ref --sort=-taggerdate --count=1  refs/tags/${TAG_PREFIX} | sed 's|.*refs/tags/||') " >> $GITHUB_ENV
              if [ -z "${CURRENT_TAG}" ]; then
                echo "NEW_TAG=${TAG_PREFIX}01" >> $GITHUB_ENV
              else 
                echo "INDEX=$(echo $CURRENT_TAG | sed \"s|.*${TAG_PREFIX}||\")" >> $GITHUB_ENV
                echo "INDEX=$((INDEX + 1))" >> $GITHUB_ENV
                [ "${INDEX}" lt 10 ] && echo "INDEX=0${INDEX}" >> $GITHUB_ENV
                echo "NEW_TAG=${TAG_PREFIX}${INDEX}" >> $GITHUB_ENV
              fi
              git tag ${NEW_TAG} -m '' && git push origin ${NEW_TAG}
        shell: bash      